//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tri_tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Musique {
            get {
                return ((string)(this["Musique"]));
            }
            set {
                this["Musique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Photos {
            get {
                return ((string)(this["Photos"]));
            }
            set {
                this["Photos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Videos {
            get {
                return ((string)(this["Videos"]));
            }
            set {
                this["Videos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initFolder {
            get {
                return ((bool)(this["initFolder"]));
            }
            set {
                this["initFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users")]
        public string LastSelectionFolder {
            get {
                return ((string)(this["LastSelectionFolder"]));
            }
            set {
                this["LastSelectionFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez d\'abord vos fichiers en les glisant dans le cadre ou en utilisant le" +
            "s boutons.\r\nPuis appuyez sur valider.")]
        public string TitreSelectionMusique {
            get {
                return ((string)(this["TitreSelectionMusique"]));
            }
            set {
                this["TitreSelectionMusique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez une ou plusieurs chanson et rentrez le nom d\'un artiste.\r\nPuis appuy" +
            "ez sur Suivant.")]
        public string TitreArtisteMusique {
            get {
                return ((string)(this["TitreArtisteMusique"]));
            }
            set {
                this["TitreArtisteMusique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez une ou plusieurs chanson et rentrez le nom d\'un album.\r\nPuis appuyez" +
            " sur Suivant.")]
        public string TitreAlbumMusique {
            get {
                return ((string)(this["TitreAlbumMusique"]));
            }
            set {
                this["TitreAlbumMusique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez une chanson et rentrez son nom.\r\nPuis appuyez sur Suivant.")]
        public string TitreChansonMusique {
            get {
                return ((string)(this["TitreChansonMusique"]));
            }
            set {
                this["TitreChansonMusique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez d\'abord les photos d\'un même album en les glisant dans le cadre ou e" +
            "n utilisant les boutons.\r\nPuis appuyez sur valider pour créer l\'album.")]
        public string TitreSelectionPhotos {
            get {
                return ((string)(this["TitreSelectionPhotos"]));
            }
            set {
                this["TitreSelectionPhotos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selectionnez d\'abord les vidéos d\'un même album en les glisant dans le cadre ou e" +
            "n utilisant les boutons.\r\nPuis appuyez sur valider pour créer l\'album.")]
        public string TitreSelectionVideos {
            get {
                return ((string)(this["TitreSelectionVideos"]));
            }
            set {
                this["TitreSelectionVideos"] = value;
            }
        }
    }
}
